namespace CrudGenerator.Core;

public sealed record StoredProcedureInfo(string Schema, string Name, DateTime ModifiedAt)
{
    public string DisplayName => $"{Schema}.{Name}";

    public static bool IsGeneratedBySpCrudGen(string? definition) =>
        !string.IsNullOrWhiteSpace(definition)
        && definition.Contains("<auto-generated>", StringComparison.OrdinalIgnoreCase)
        && definition.Contains("sp_CRUDGen", StringComparison.OrdinalIgnoreCase);
}
