using CrudGenerator.Core;

namespace CrudGenerator.Core.Tests;

public sealed class StoredProcedureInfoTests
{
    [Fact]
    public void DisplayName_UsesSchemaQualifiedName()
    {
        var subject = new StoredProcedureInfo("sales", "OrderRead", DateTime.UnixEpoch);

        Assert.Equal("sales.OrderRead", subject.DisplayName);
    }

    [Theory]
    [InlineData("/* <auto-generated> generated from dbo.sp_CRUDGen </auto-generated> */", true)]
    [InlineData("/* <AUTO-GENERATED> generated from dbo.SP_CRUDGEN </AUTO-GENERATED> */", true)]
    [InlineData("CREATE PROCEDURE dbo.ManualProcedure AS SELECT 1", false)]
    [InlineData("/* <auto-generated> generated by another tool </auto-generated> */", false)]
    [InlineData(null, false)]
    public void IsGeneratedBySpCrudGen_RequiresBothUpstreamMarkers(string? definition, bool expected)
    {
        Assert.Equal(expected, StoredProcedureInfo.IsGeneratedBySpCrudGen(definition));
    }
}
